/**********************************************************************
Project: 	  Data & Intelligence Platform - Heritage

Program Name: 203_excl_final_003_previous_campaign_variables.sas

Overview:     STUB AT PRESENT
              
***********************************************************************
                  DEPENDENCIES AND LIMITATIONS
      
 
Parameter(s):  None

Dependencies:  None


***********************************************************************
                    CHANGE CONTROL LOG 

Change log (in reverse chronological order) :-

June2019  	KM  Migration to DIP
2015-2019  	Original EXCL development on Heritage Platform by
            Richard Holley and members of the Analytics Team.
            	 
                                      
***********************************************************************/
%put INFO-203_excl_final_003_previous_campaign_variables.sas: STUB AT PRESENT;
%GetStarted;
/*establish what letters/text we have sent in the last 30 days. These need to be taken into account so we don't accidentally campaign customers that have just been sent
a letter/text*/
PROC SQL;
CONNECT TO ORACLE AS MYORACON (USER="&ORADW_USER1" PASSWORD="&ORADW_PASS1" PATH=DWP);
CREATE TABLE ExclWork.LETTER_OR_TEXT AS SELECT * FROM CONNECTION TO MYORACON (
        SELECT B.IRD_NUMBER,
               B.LOCATION_NUMBER,
               A.COMMUNICATION_ID,
               A.COMM_START_DATE,
               A.COMM_END_DATE,
               A.COMM_DESC,
               A.CHANNEL
          FROM "67AWCH".CMP_COMMUNICATION A
    INNER JOIN "67AWCH".CMP_MASTER        B ON A.COMMUNICATION_ID = B.COMMUNICATION_ID
         WHERE UPPER(A.CHANNEL) IN ('LETTER','TEXT MESSAGE') AND
               A.COMM_START_DATE > SYSDATE - 30);
DISCONNECT FROM MYORACON;
QUIT;

PROC SORT DATA = ExclWork.LETTER_OR_TEXT; BY IRD_NUMBER LOCATION_NUMBER COMM_END_DATE; RUN;
DATA ExclWork.LETTER_OR_TEXT; SET ExclWork.LETTER_OR_TEXT; BY IRD_NUMBER LOCATION_NUMBER COMM_END_DATE; IF LAST.IRD_NUMBER THEN OUTPUT; RUN;

DATA CMP_PREVIOUS_CAMPAIGN_VARIABLES;
	MERGE EXCLTEMP.PREV_CMPS_UNIQUE           (IN=A RENAME=(COMM_ID = COMMID COMM_DESC =DESCRIPTION COMM_START_DATE = COMMSTARTDATE COMM_END_DATE = COMMENDDATE COMM_SHORT_DESC = COMMSHORTDESC CASE_NUMBER = CASENUMBERPREVCMP  BILATERAL = BILATERAL) )
          EXCLTEMP.PREV_CMPS_UNIQUE_B10       (IN=C DROP= CASE_NUMBER BILATERAL RENAME=( COMM_ID = COMMIDB10 COMM_DESC =DESCRIPTIONB10 COMM_START_DATE = COMMSTARTDATEB10 COMM_END_DATE = COMMENDDATEB10 COMM_SHORT_DESC = COMMSHORTDESCB10 ))
          EXCLTEMP.PREV_CMPS_UNIQUE_BAU       (IN=D DROP= CASE_NUMBER RENAME=( COMM_ID = COMMIDBAU COMM_DESC =DESCRIPTIONBAU COMM_START_DATE = COMMSTARTDATEBAU COMM_END_DATE = COMMENDDATEBAU COMM_SHORT_DESC = COMMSHORTDESCBAU ))
          EXCLTEMP.PREV_CMPS_UNIQUE_CCO       (IN=E DROP= CASE_NUMBER RENAME=( COMM_ID = COMMIDCCO COMM_DESC =DESCRIPTIONCCO COMM_START_DATE = COMMSTARTDATECCO COMM_END_DATE = COMMENDDATECCO COMM_SHORT_DESC = COMMSHORTDESCCCO ))
          EXCLTEMP.PREV_CMPS_UNIQUE_CS        (IN=F DROP= CASE_NUMBER RENAME=(COMM_ID = COMMIDCS COMM_DESC =DESCRIPTIONCS COMM_START_DATE = COMMSTARTDATECS COMM_END_DATE = COMMENDDATECS COMM_SHORT_DESC = COMMSHORTDESCCS ))
          EXCLTEMP.PREV_CMPS_UNIQUE_SL        (IN=G DROP= CASE_NUMBER RENAME=(COMM_ID = COMMIDSL COMM_DESC =DESCRIPTIONSL COMM_START_DATE = COMMSTARTDATESL COMM_END_DATE = COMMENDDATESL COMM_SHORT_DESC = COMMSHORTDESCSL ))
          EXCLTEMP.PREV_CMPS_UNIQUE_B12_RTNS  (IN=H DROP= CASE_NUMBER RENAME=(COMM_ID = COMMIDB12RTNS COMM_DESC =DESCRIPTIONB12RTNS COMM_START_DATE = COMMSTARTDATEB12RTNS COMM_END_DATE = COMMENDDATEB12RTNS COMM_SHORT_DESC = COMMSHORTDESCB12RTNS ))
          EXCLTEMP.PREV_CMPS_UNIQUE_B12       (IN=H DROP= CASE_NUMBER RENAME=(COMM_ID = COMMIDB12 COMM_DESC =DESCRIPTIONB12 COMM_START_DATE = COMMSTARTDATEB12 COMM_END_DATE = COMMENDDATEB12 COMM_SHORT_DESC = COMMSHORTDESCB12 ))
          ExclWork.LETTER_OR_TEXT             (IN=J RENAME=(COMMUNICATION_ID = COMMIDLETTERTEXT  COMM_START_DATE=COMMSTARTDATELETTERTEXT COMM_END_DATE =COMMENDDATELETTERTEXT COMM_DESC = COMMSHORTDESCLETTERTEXT CHANNEL=CHANNELLETTERTEXT));
	BY IRD_NUMBER LOCATION_NUMBER;
	IF A THEN DO;
		 IRDNUMBERPREVCMP = IRD_NUMBER;
		 LOCATIONNUMBERPREVCMP=	LOCATION_NUMBER;
		 END;
RUN;

PROC SORT DATA=CMP_PREVIOUS_CAMPAIGN_VARIABLES DUPOUT=DUPE_TEST NODUPKEY; BY IRD_NUMBER; RUN;
PROC SQL;
CONNECT TO ORACLE AS MYORACON (USER="&ORADW_USER1" PASSWORD="&ORADW_PASS1"  PATH=DWP);
CREATE TABLE EXCLTEMP.PREV_DFIA AS SELECT * FROM CONNECTION TO MYORACON (
        SELECT AL1.IRD_NUMBER AS IRD_NUMBER_PRV_DFIA,
               COUNT(AL1.COMMUNICATION_ID) AS PRV_DFIA_COUNT,
               MAX(AL2.COMM_START_DATE) AS CMP_MAX_START_DATE
          FROM "67AWCH".CMP_MASTER        AL1 
    INNER JOIN "67AWCH".CMP_COMMUNICATION AL2 ON AL1.COMMUNICATION_ID = AL2.COMMUNICATION_ID
         WHERE AL2.PROGRAMME_ID IN (254,289) AND 
               AL2.COMM_ROUND = 1 AND
               AL2.COMM_START_DATE > SYSDATE - 545 /* 545DAYS = 18 MONTHS */
      GROUP BY AL1.IRD_NUMBER);
DISCONNECT FROM MYORACON;
QUIT;

PROC SORT DATA=EXCLTEMP.PREV_DFIA; BY IRD_NUMBER_PRV_DFIA; RUN;

DATA ExclTemp.CMP_PREVIOUS_CAMPAIGN_VARIABLES (DROP= LOCATION_NUMBER CMP_MAX_START_DATE CLOSED_CAMPAIGN_PORTFOLIO: RENAME=(IRD_NUMBER=IRDNUMBER));
MERGE CMP_PREVIOUS_CAMPAIGN_VARIABLES (IN=A) 		  
	  ExclTemp.PREV_DFIA (IN=B RENAME=(IRD_NUMBER_PRV_DFIA = IRD_NUMBER PRV_DFIA_COUNT  = PREVDFIACOUNT))
	  ExclTemp.CMP_REFERRALS_UNIQUE (IN=J)
	  ExclTemp.LEADS_TOTAL (IN=K RENAME=(LEAD_TYPE_RET = LEADTYPERET CURRENT_CAMPAIGN_PORTFOLIO_RET =CURRENTCAMPAIGNPORTFOLIORET CURRENTLY_CAMPAIGNED_RET = CURRENTLYCAMPAIGNEDRET
						    CLOSED_LEAD_RET =CLOSEDLEADRET  CLOSED_CAMPAIGNED_RET =CLOSEDCAMPAIGNEDRET CLOSED_DATE_RET =CLOSEDDATERET DAYS_SINCE_CLOSED_RET = DAYSSINCECLOSEDRET
						    LEAD_TYPE_COL =LEADTYPECOL CURRENT_CAMPAIGN_PORTFOLIO_COL = CURRENTCAMPAIGNPORTFOLIOCOL CURRENTLY_CAMPAIGNED_COL = CURRENTLYCAMPAIGNEDCOL
							CLOSED_LEAD_COL =CLOSEDLEADCOL CLOSED_CAMPAIGNED_COL =CLOSEDCAMPAIGNEDCOL CLOSED_DATE_COL =CLOSEDDATECOL DAYS_SINCE_CLOSED_COL=DAYSSINCECLOSEDCOL
							LEAD_TYPE_CS =LEADTYPECS  CURRENT_CAMPAIGN_PORTFOLIO_CS =CURRENTCAMPAIGNPORTFOLIOCS CURRENTLY_CAMPAIGNED_CS = CURRENTLYCAMPAIGNEDCS CLOSED_LEAD_CS= CLOSEDLEADCS
							CLOSED_CAMPAIGNED_CS  = CLOSEDCAMPAIGNEDCS CLOSED_DATE_CS =CLOSEDDATECS DAYS_SINCE_CLOSED_CS =DAYSSINCECLOSEDCS
							LEAD_TYPE_CC = LEADTYPECC CURRENT_CAMPAIGN_PORTFOLIO_CC = CURRENTCAMPAIGNPORTFOLIOCC CURRENTLY_CAMPAIGNED_CC = CURRENTLYCAMPAIGNEDCC
							CLOSED_LEAD_CC = CLOSEDLEADCC  CLOSED_CAMPAIGNED_CC = CLOSEDCAMPAIGNEDCC CLOSED_DATE_CC = CLOSEDDATECC DAYS_SINCE_CLOSED_CC =DAYSSINCECLOSEDCC
							LEAD_TYPE_INV = LEADTYPEINV CURRENT_CAMPAIGN_PORTFOLIO_INV = CURRENTCAMPAIGNPORTFOLIOINV CURRENTLY_CAMPAIGNED_INV = CURRENTLYCAMPAIGNEDINV
							CLOSED_LEAD_INV = CLOSEDLEADINV  CLOSED_CAMPAIGNED_INV = CLOSEDCAMPAIGNEDINV CLOSED_DATE_INV = CLOSEDDATEINV DAYS_SINCE_CLOSED_INV =DAYSSINCECLOSEDINV));
BY IRD_NUMBER;
IF A OR B OR J OR K;
IF LEADTYPERET   NE 'Y' THEN LEADTYPERET   = 'N';
IF CLOSEDLEADRET NE 'Y' THEN CLOSEDLEADRET = 'N';
IF LEADTYPECOL   NE 'Y' THEN LEADTYPECOL   = 'N';
IF CLOSEDLEADCOL NE 'Y' THEN CLOSEDLEADCOL = 'N';
IF LEADTYPECS    NE 'Y' THEN LEADTYPECS    = 'N';
IF CLOSEDLEADCS  NE 'Y' THEN CLOSEDLEADCS  = 'N';
IF LEADTYPECC    NE 'Y' THEN LEADTYPECC    = 'N';
IF CLOSEDLEADCC  NE 'Y' THEN CLOSEDLEADCC  = 'N';
IF LEADTYPEINV   NE 'Y' THEN LEADTYPEINV   = 'N';
IF CLOSEDLEADINV NE 'Y' THEN CLOSEDLEADINV = 'N';


RUN;



%ErrCheck;